
--Brazilian E-Commerce Analysis------------------

--1.Retrieve the total number of customers percentage per state.Keep in Desc Order
Select
customer_state,
Count (customer_id) AS Total_Customer,
COUNT (customer_id) * 100 / SUM (Count (customer_id)) over ()As Percentage_Customer 
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_customers_dataset] 
GROUP by customer_state
ORDER by Percentage_Customer  Desc;

--2.List all unique cities in the customer_city column,Specify top 10.
Select
Distinct TOP 10 customer_city 
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_customers_dataset] 

--3.Identify the states with the most geolocation entries.
SELECT
Top 1
["geolocation_state"],
COUNT (["geolocation_zip_code_prefix"]) As geolocation_entries
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_geolocation_dataset] 
GROUP By ["geolocation_state"]
ORDER by geolocation_entries Desc;

--4.Find all cities where the geolocation_zip_code_prefix is shared by more than one city.
SELECT 
TOP 5
["geolocation_city"],
["geolocation_zip_code_prefix"]
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_geolocation_dataset]
WHERE ["geolocation_zip_code_prefix"]
IN 
(SELECT["geolocation_zip_code_prefix"]
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_geolocation_dataset]
GROUP BY ["geolocation_zip_code_prefix"]
HAVING COUNT(DISTINCT ["geolocation_city"]) > 1 );

--5.Retrieve the highest revenue (price) from all orders.
SELECT
MAX (["price"]) As Highest_Revenue
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_items_dataset]

--6.Calculate the Max freight_value for delivered orders.
SELECT
(MAX (["freight_value"]) As Highets_Freight
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_items_dataset]

--7.Count the number of orders made using each payment_type.
SELECT
payment_type,
Count (order_id) As No_of_Orders
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_payments_dataset]
GROUP by payment_type
ORDER BY No_of_Orders Desc;

--8.Find the top 5 total payment_value for orders with more than one installment.
SELECT
Top 5
[payment_installments],
SUM(CAST([payment_value] AS FLOAT)) AS Total_Payment_Value
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_payments_dataset]
WHERE [payment_installments] > 1
GROUP BY [payment_installments]
ORDER BY Total_Payment_Value DESC;

--9.Retrieve the list of top 5  orders that were delivered after their estimated delivery date.
SELECT TOP 5 
["order_id"],
["order_estimated_delivery_date"],
["order_delivered_customer_date"],
DATEDIFF(DAY, ["order_estimated_delivery_date"], ["order_delivered_customer_date"]) AS Delay_In_Days
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_orders_dataset]
WHERE ["order_delivered_customer_date"] > ["order_estimated_delivery_date"]
ORDER BY Delay_In_Days DESC;

--10.Calculate the average delivery time for orders 
SELECT 
AVG(DATEDIFF(DAY, ["order_purchase_timestamp"], ["order_delivered_customer_date"])) AS Average_Delivery_Time
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_orders_dataset]
WHERE ["order_delivered_customer_date"] IS NOT NULL 
AND ["order_purchase_timestamp"] IS NOT NULL;

--11.Find the top 10 total revenue (price) generated by each seller by joining Order_Item and Seller_Dataset
SELECT 
Top 10
[Brazilian E-Commerce  Dataset ].[dbo].[olist_sellers_dataset].["seller_id"],
ROUND (SUM(CAST([Brazilian E-Commerce  Dataset ].[dbo].[olist_order_items_dataset].["price"] AS FLOAT)),2) AS "Total_Revenue"
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_sellers_dataset] 
LEFT JOIN [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_items_dataset]
ON [Brazilian E-Commerce  Dataset ].[dbo].[olist_sellers_dataset].["seller_id"] = [Brazilian E-Commerce  Dataset ].[dbo].[olist_order_items_dataset].["seller_id"]
GROUP BY [Brazilian E-Commerce  Dataset ].[dbo].[olist_sellers_dataset].["seller_id"]
ORDER BY "Total_Revenue" Desc;

--12. Find top 10 Seller state, keep order in Desc order
SELECT
Top 10
["seller_state"],
COUNT (["seller_id"]) As No_of_sellers
FROM [Brazilian E-Commerce  Dataset ].[dbo].[olist_sellers_dataset]
Group by ["seller_state"]
ORDER by No_of_sellers Desc;






